# ```
# singularity\singularity-server>  docker build -t singularity-gw:1.0.0 -f Dockerfiles/Dockerfile .
# ```
FROM tensorflow/serving
LABEL name="rhslrhs"

ENV TZ=Asia/Seoul
ENV MODEL_BASE_PATH=/models
ENV MODEL_NAME=numImage

COPY tf-mymodel/ $MODEL_BASE_PATH/numImage

## change rest-api-port
RUN sed -i 's@8501@11300@g' /usr/bin/tf_serving_entrypoint.sh

EXPOSE 11300

ENTRYPOINT ["/usr/bin/tf_serving_entrypoint.sh"]
