# ```
# singularity\singularity-server>  docker build -t singularity-gw:1.0.0 -f Dockerfiles/Dockerfile .
# ```
FROM tensorflow/serving
LABEL name="rhslrhs"

ENV TZ=Asia/Seoul
ENV MODEL_BASE_PATH=/models
ENV MODEL_NAME=tf-mymodel

COPY tf-mymodel/ $MODEL_BASE_PATH/tf-mymodel

## change rest-api-port
CMD sed -i 's@8501@11300@g' /usr/bin/tf_serving_entrypoint.sh

EXPOSE 8500 8501

ENTRYPOINT ["/usr/bin/tf_serving_entrypoint.sh"]
